# Generated by Django 2.0.6 on 2018-11-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181105_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_operate_author', 'Creat, update or delete authors'),)},
        ),
    ]
